// Code generated by Slice Machine. DO NOT EDIT.

import Image from "./Image";
import NavigationItem from "./NavigationItem";
import Quote from "./Quote";
import Text from "./Text";

export { Image, NavigationItem, Quote, Text };

export const components = {
  image: Image,
  nav_item: NavigationItem,
  quote: Quote,
  text: Text,
};
