// Code generated by Slice Machine. DO NOT EDIT.

import NavigationItem from './NavigationItem';
import Text from './Text';

export {
	NavigationItem,
	Text,
};

export const components = {
	nav_item: NavigationItem,
	text: Text,
};
